export type SupplierDirectoryEntry = {
  id: string; name: string; region: "INDIA" | "CHINA" | "GLOBAL"; supplierType: "DISTRIBUTOR" | "MARKETPLACE" | "PCB_MANUFACTURER" | "PROTOTYPING_SERVICE" | "CONTRACT_MANUFACTURER" | "INJECTION_MOULDING" | "THREE_D_PRINTING" | "ELECTRONICS_ASSEMBLY" | "PACKAGING" | "TESTING_LAB";
  specialties: string[]; minimumOrderNotes: string; suitableVolumes: number[]; officialHomepage: string; searchUrlTemplate: string | null; verificationLevel: "AUTHORISED_DISTRIBUTOR" | "ESTABLISHED_SERVICE" | "MARKETPLACE" | "DIRECTORY_LEAD" | "UNVERIFIED_LEAD"; lastReviewed: string; warning: string;
};

export const CURATED_SUPPLIERS: SupplierDirectoryEntry[] = [
  { id: "robu", name: "Robu", region: "INDIA", supplierType: "DISTRIBUTOR", specialties: ["Electronics", "robotics", "prototype parts"], minimumOrderNotes: "Check product-level minimums and stock.", suitableVolumes: [1, 10, 100], officialHomepage: "https://robu.in/", searchUrlTemplate: "https://robu.in/?s={query}&post_type=product", verificationLevel: "ESTABLISHED_SERVICE", lastReviewed: "2026-07-27", warning: "Verify manufacturer traceability, stock and specification before purchasing." },
  { id: "electronicscomp", name: "ElectronicsComp", region: "INDIA", supplierType: "DISTRIBUTOR", specialties: ["Electronic components", "modules", "tools"], minimumOrderNotes: "Product-level terms vary.", suitableVolumes: [1, 10, 100], officialHomepage: "https://www.electronicscomp.com/", searchUrlTemplate: "https://www.electronicscomp.com/catalogsearch/result/?q={query}", verificationLevel: "ESTABLISHED_SERVICE", lastReviewed: "2026-07-27", warning: "Verify stock, brand and traceability for production use." },
  { id: "element14", name: "element14 India", region: "INDIA", supplierType: "DISTRIBUTOR", specialties: ["Authorised electronic components", "development tools"], minimumOrderNotes: "Pack sizes and minimums vary by manufacturer.", suitableVolumes: [1, 10, 100, 1000], officialHomepage: "https://in.element14.com/", searchUrlTemplate: "https://in.element14.com/search?st={query}", verificationLevel: "AUTHORISED_DISTRIBUTOR", lastReviewed: "2026-07-27", warning: "Authorised distributor listing; verify stock and manufacturer traceability." },
  { id: "mouser", name: "Mouser India", region: "INDIA", supplierType: "DISTRIBUTOR", specialties: ["Authorised electronic components"], minimumOrderNotes: "Manufacturer pack quantities and shipping terms vary.", suitableVolumes: [1, 10, 100, 1000], officialHomepage: "https://www.mouser.in/", searchUrlTemplate: "https://www.mouser.in/c/?q={query}", verificationLevel: "AUTHORISED_DISTRIBUTOR", lastReviewed: "2026-07-27", warning: "Authorised distributor listing; verify stock and manufacturer traceability." },
  { id: "digikey", name: "DigiKey India", region: "INDIA", supplierType: "DISTRIBUTOR", specialties: ["Authorised electronic components"], minimumOrderNotes: "Manufacturer pack quantities and import terms vary.", suitableVolumes: [1, 10, 100, 1000], officialHomepage: "https://www.digikey.in/", searchUrlTemplate: "https://www.digikey.in/en/products/result?keywords={query}", verificationLevel: "AUTHORISED_DISTRIBUTOR", lastReviewed: "2026-07-27", warning: "Authorised distributor listing; verify stock and manufacturer traceability." },
  { id: "indiamart", name: "IndiaMART", region: "INDIA", supplierType: "MARKETPLACE", specialties: ["Supplier discovery", "fabrication", "packaging"], minimumOrderNotes: "Each seller sets its own MOQ and terms.", suitableVolumes: [10, 100, 1000, 10000], officialHomepage: "https://www.indiamart.com/", searchUrlTemplate: "https://dir.indiamart.com/search.mp?ss={query}", verificationLevel: "MARKETPLACE", lastReviewed: "2026-07-27", warning: "Marketplace — independently verify the seller, capability, quality and commercial terms." },
  { id: "lcsc", name: "LCSC", region: "CHINA", supplierType: "DISTRIBUTOR", specialties: ["Electronic components", "PCB supply chain"], minimumOrderNotes: "Pack sizes, export and shipping terms vary.", suitableVolumes: [10, 100, 1000, 10000], officialHomepage: "https://www.lcsc.com/", searchUrlTemplate: "https://www.lcsc.com/search?q={query}", verificationLevel: "ESTABLISHED_SERVICE", lastReviewed: "2026-07-27", warning: "Verify manufacturer, traceability, import duties and landed cost." },
  { id: "jlcpcb", name: "JLCPCB", region: "CHINA", supplierType: "PCB_MANUFACTURER", specialties: ["PCB fabrication", "PCB assembly", "prototype manufacturing"], minimumOrderNotes: "Quote depends on board files, stack-up and assembly scope.", suitableVolumes: [1, 10, 100, 1000], officialHomepage: "https://jlcpcb.com/", searchUrlTemplate: null, verificationLevel: "ESTABLISHED_SERVICE", lastReviewed: "2026-07-27", warning: "Upload only design files you are authorised to share; verify quality and import terms." },
  { id: "pcbway", name: "PCBWay", region: "CHINA", supplierType: "PCB_MANUFACTURER", specialties: ["PCB fabrication", "assembly", "3D printing", "CNC"], minimumOrderNotes: "Quotation depends on uploaded design and process details.", suitableVolumes: [1, 10, 100, 1000], officialHomepage: "https://www.pcbway.com/", searchUrlTemplate: null, verificationLevel: "ESTABLISHED_SERVICE", lastReviewed: "2026-07-27", warning: "Verify manufacturability, quality requirements, IP handling and import terms." },
  { id: "alibaba", name: "Alibaba", region: "GLOBAL", supplierType: "MARKETPLACE", specialties: ["Supplier discovery", "contract manufacturing", "tooling"], minimumOrderNotes: "Seller-specific MOQ and terms apply.", suitableVolumes: [100, 1000, 10000], officialHomepage: "https://www.alibaba.com/", searchUrlTemplate: "https://www.alibaba.com/trade/search?SearchText={query}", verificationLevel: "MARKETPLACE", lastReviewed: "2026-07-27", warning: "Marketplace — independently audit the supplier, samples, quality system and commercial terms." },
  { id: "aliexpress", name: "AliExpress", region: "GLOBAL", supplierType: "MARKETPLACE", specialties: ["Prototype-quantity commodity parts"], minimumOrderNotes: "Suitable only for exploratory prototype quantities where traceability is not required.", suitableVolumes: [1, 10], officialHomepage: "https://www.aliexpress.com/", searchUrlTemplate: "https://www.aliexpress.com/wholesale?SearchText={query}", verificationLevel: "MARKETPLACE", lastReviewed: "2026-07-27", warning: "Prototype sourcing lead only; not recommended as evidence of production-quality supply." },
];

export function supplierResultsStale(checkedAt: string | null, now = new Date(), days = 14) {
  if (!checkedAt) return true;
  const checked = new Date(checkedAt);
  return Number.isNaN(checked.valueOf()) || now.valueOf() - checked.valueOf() > days * 86_400_000;
}
