import type { GovernmentScheme, ProgrammeType } from "./types";

const reviewed = "2026-07-26";
const source = (title: string, url: string) => ({ title, url, hostname: new URL(url).hostname, checkedAt: reviewed });
const common = {
  sourceType: "CURATED" as const,
  maximumDirectGrantInr: null,
  maximumOtherSupportInr: null,
  currentlyOpenStatus: "NOT_VERIFIED" as const,
  deadlineStatus: "NO_ACTIVE_DEADLINE_VERIFIED" as const,
  deadlineText: "No active deadline verified — check the official portal.",
  difficulty: "MEDIUM" as const,
  lastReviewed: reviewed,
  confidence: "HIGH" as const,
  evidence: {},
  verificationWarnings: ["Current calls, limits and eligibility must be checked on the official portal."],
  commonlyRequestedDocuments: ["Applicant registration documents", "Invention or venture summary", "Prototype or validation plan", "Budget and milestone plan"],
};

function scheme(input: Partial<GovernmentScheme> & Pick<GovernmentScheme, "id" | "name" | "agency" | "ministry" | "programmeType" | "supportType" | "fundingLabel" | "fundingInstrument" | "summary" | "eligibilityRequirements" | "hardRequirements" | "preferredDomains" | "preferredStages" | "supportedApplicantTypes" | "whatItSupports" | "applicationMethod" | "applicationSteps" | "officialPortal" | "officialSources">): GovernmentScheme {
  return { ...common, ...input } as GovernmentScheme;
}

const generalDomains: GovernmentScheme["preferredDomains"] = ["GENERAL_INNOVATION", "HARDWARE", "ELECTRONICS", "SOFTWARE", "HEALTHCARE", "MEDTECH", "AGRITECH", "CLEANTECH", "MANUFACTURING", "SOCIAL_IMPACT"];
const startupApplicants = ["dpiit_startup", "startup_without_dpiit", "individual", "student", "researcher"];

export const CURATED_GOVERNMENT_SCHEMES: GovernmentScheme[] = [
  scheme({ id: "sisfs", name: "Startup India Seed Fund Scheme (SISFS)", aliases: ["SISFS"], agency: "DPIIT", ministry: "Ministry of Commerce and Industry", programmeType: "DIRECT_GRANT", supportType: ["prototype", "commercialisation", "startup"], fundingLabel: "Up to ₹20 lakh as grant for proof of concept, prototype or product trials; separate debt/convertible support may be available up to ₹50 lakh", maximumDirectGrantInr: 2_000_000, maximumOtherSupportInr: 5_000_000, fundingInstrument: "Grant; separate debt or convertible instrument", summary: "Seed support delivered through approved incubators for eligible early-stage startups.", eligibilityRequirements: ["DPIIT-recognised startup", "Incorporated not more than two years before application", "Innovative, scalable business idea"], hardRequirements: ["dpiit_yes", "incorporated_under_two_years_yes"], preferredDomains: generalDomains, preferredStages: ["idea", "proof_of_concept", "prototype", "pilot"], supportedApplicantTypes: ["dpiit_startup"], whatItSupports: ["Proof of concept", "Prototype development", "Product trials", "Market entry and commercialisation"], applicationMethod: "Apply through the Startup India Seed Fund portal and eligible incubators.", applicationSteps: ["Verify DPIIT and incorporation-age eligibility", "Create or update the Startup India profile", "Apply to eligible incubators through the official portal"], officialPortal: "https://seedfund.startupindia.gov.in/", officialSources: [source("Startup India Seed Fund Scheme", "https://seedfund.startupindia.gov.in/"), source("SISFS guidelines", "https://www.startupindia.gov.in/content/dam/invest-india/Templates/public/Guidelines%20for%20Startup%20India%20Seed%20Fund%20Scheme.pdf")], evidence: { funding: "Official scheme guidance separates grant support from debt or convertible support.", eligibility: "DPIIT recognition and incorporation-age requirements apply." } }),
  scheme({ id: "nidhi-prayas", name: "NIDHI-PRAYAS", agency: "Department of Science and Technology", ministry: "Ministry of Science and Technology", programmeType: "PROTOTYPE_SUPPORT", supportType: ["prototype", "incubation"], fundingLabel: "Prototype-development support through selected PRAYAS centres; current ceiling must be verified", fundingInstrument: "Prototype grant/support", summary: "Supports innovators converting technology ideas into proof-of-concept prototypes.", eligibilityRequirements: ["Technology-led physical product or prototype", "Application through a PRAYAS centre"], hardRequirements: [], preferredDomains: ["HARDWARE", "ELECTRONICS", "MEDTECH", "AGRITECH", "CLEANTECH", "MANUFACTURING"], preferredStages: ["idea", "proof_of_concept", "prototype"], supportedApplicantTypes: ["individual", "student", "researcher", ...startupApplicants], whatItSupports: ["Prototype development", "Testing and technical validation", "Incubator access"], applicationMethod: "Apply through a participating NIDHI-PRAYAS centre when a call is open.", applicationSteps: ["Review current PRAYAS guidelines", "Identify a participating centre", "Submit the prototype proposal through that centre"], officialPortal: "https://nidhi.dst.gov.in/", officialSources: [source("NIDHI programme portal", "https://nidhi.dst.gov.in/"), source("NIDHI programme guidelines", "https://nidhi.dst.gov.in/document-category/programme-guidelines/")] }),
  scheme({ id: "nidhi-eir", name: "NIDHI Entrepreneur-in-Residence (EIR)", agency: "Department of Science and Technology", ministry: "Ministry of Science and Technology", programmeType: "FELLOWSHIP", supportType: ["fellowship", "incubation"], fundingLabel: "Entrepreneurship fellowship; current stipend and call terms must be verified", fundingInstrument: "Fellowship", summary: "Provides aspiring technology entrepreneurs time and support to pursue a venture idea.", eligibilityRequirements: ["Aspiring technology entrepreneur", "Selection through an approved programme centre"], hardRequirements: [], preferredDomains: generalDomains, preferredStages: ["idea", "proof_of_concept"], supportedApplicantTypes: ["individual", "student", "researcher"], whatItSupports: ["Founder subsistence", "Mentoring", "Venture formation"], applicationMethod: "Apply through an authorised NIDHI-EIR programme centre.", applicationSteps: ["Review programme guidelines", "Locate an authorised centre", "Submit the required entrepreneur proposal"], officialPortal: "https://nidhi.dst.gov.in/", officialSources: [source("NIDHI schemes", "https://nidhi.dst.gov.in/schemes-programmes/")] }),
  scheme({ id: "nidhi-ssp", name: "NIDHI Seed Support Programme", agency: "Department of Science and Technology", ministry: "Ministry of Science and Technology", programmeType: "OTHER", supportType: ["commercialisation", "startup"], fundingLabel: "Seed support through eligible incubators; instrument and ceiling depend on the current programme", fundingInstrument: "Seed support; terms vary", summary: "Early-stage financial support delivered through selected technology business incubators.", eligibilityRequirements: ["Innovation-led startup associated with an eligible incubator"], hardRequirements: [], preferredDomains: generalDomains, preferredStages: ["prototype", "pilot", "market_ready"], supportedApplicantTypes: startupApplicants, whatItSupports: ["Product development", "Market validation", "Commercialisation"], applicationMethod: "Approach an incubator participating in NIDHI-SSP.", applicationSteps: ["Review current guidelines", "Identify a participating incubator", "Submit venture and milestone information"], officialPortal: "https://nidhi.dst.gov.in/", officialSources: [source("NIDHI programme guidelines", "https://nidhi.dst.gov.in/document-category/programme-guidelines/")] }),
  scheme({ id: "fund-of-funds", name: "Startup India Fund of Funds", aliases: ["FFS", "Fund of Funds for Startups"], agency: "SIDBI", ministry: "DPIIT, Ministry of Commerce and Industry", programmeType: "INDIRECT_INVESTMENT", supportType: ["startup", "commercialisation"], fundingLabel: "Indirect investment through SEBI-registered Alternative Investment Funds; not a direct grant to startups", fundingInstrument: "Indirect equity investment", summary: "Government corpus invested through eligible AIFs, which in turn invest in startups.", eligibilityRequirements: ["Investment consideration by a participating AIF"], hardRequirements: [], preferredDomains: generalDomains, preferredStages: ["prototype", "pilot", "market_ready", "revenue"], supportedApplicantTypes: ["dpiit_startup", "startup_without_dpiit", "existing_company"], whatItSupports: ["Growth capital through participating investment funds"], applicationMethod: "Startups approach participating AIFs; SIDBI does not award a direct grant.", applicationSteps: ["Review the official Fund of Funds structure", "Identify participating AIFs", "Approach a fund under its investment process"], officialPortal: "https://www.sidbivcf.in/en/funds/ffs", officialSources: [source("SIDBI Fund of Funds for Startups", "https://www.sidbivcf.in/en/funds/ffs"), source("Startup India funding overview", "https://www.startupindia.gov.in/content/sih/en/looking_for_funding.html")] }),
  scheme({ id: "tdb", name: "Technology Development Board Assistance", agency: "Technology Development Board", ministry: "Department of Science and Technology", programmeType: "LOAN", supportType: ["commercialisation", "loan"], fundingLabel: "Loan, equity or grant support may be considered under programme terms; verify the current call", fundingInstrument: "Loan, equity or grant depending on project", summary: "Assistance for development and commercial application of indigenous technology.", eligibilityRequirements: ["Commercialisation of indigenous technology", "Technically and commercially viable project"], hardRequirements: [], preferredDomains: ["HARDWARE", "ELECTRONICS", "MANUFACTURING", "MATERIALS", "MEDTECH", "CLEANTECH", "ENERGY"], preferredStages: ["prototype", "pilot", "market_ready", "revenue"], supportedApplicantTypes: ["small_entity", "existing_company", "dpiit_startup"], whatItSupports: ["Technology development", "Scale-up", "Commercial application"], applicationMethod: "Submit through the official TDB application process.", applicationSteps: ["Review current assistance criteria", "Prepare technical and commercial project reports", "Submit through the official portal"], officialPortal: "https://tdb.gov.in/", officialSources: [source("Technology Development Board", "https://tdb.gov.in/")] }),
  scheme({ id: "atal-incubation", name: "Atal Incubation Centres", agency: "Atal Innovation Mission", ministry: "NITI Aayog", programmeType: "INCUBATION_SUPPORT", supportType: ["incubation", "startup"], fundingLabel: "Incubation, mentoring and ecosystem access; not a direct government grant to every applicant", fundingInstrument: "Incubation and non-financial support", summary: "Network of incubation centres supporting innovative startups and entrepreneurs.", eligibilityRequirements: ["Selection under an individual incubation centre's programme"], hardRequirements: [], preferredDomains: generalDomains, preferredStages: ["idea", "proof_of_concept", "prototype", "pilot"], supportedApplicantTypes: startupApplicants, whatItSupports: ["Incubation", "Mentoring", "Infrastructure", "Investor and ecosystem access"], applicationMethod: "Approach a listed Atal Incubation Centre and verify its current intake.", applicationSteps: ["Find a relevant centre", "Check its current application window", "Apply under the centre's published process"], officialPortal: "https://aim.gov.in/atal-incubation-centres.php", officialSources: [source("Atal Incubation Centres", "https://aim.gov.in/atal-incubation-centres.php")] }),
  scheme({ id: "anic", name: "Atal New India Challenge", aliases: ["ANIC"], agency: "Atal Innovation Mission", ministry: "NITI Aayog", programmeType: "COMPETITION", supportType: ["prototype", "commercialisation", "competition"], fundingLabel: "Challenge-based support; amounts and open challenge statements must be verified", fundingInstrument: "Challenge grant/support", summary: "Challenge-led programme for technology solutions aligned to published problem statements.", eligibilityRequirements: ["Solution must address a current published challenge"], hardRequirements: [], preferredDomains: generalDomains, preferredStages: ["prototype", "pilot", "market_ready"], supportedApplicantTypes: startupApplicants, whatItSupports: ["Product development", "Testing", "Deployment against challenge statements"], applicationMethod: "Apply only against an active official challenge call.", applicationSteps: ["Review active challenge statements", "Confirm solution fit", "Apply through the official call"], officialPortal: "https://aim.gov.in/", officialSources: [source("Atal Innovation Mission", "https://aim.gov.in/")] }),
  scheme({ id: "birac-big", name: "Biotechnology Ignition Grant (BIG)", aliases: ["BIG"], agency: "BIRAC", ministry: "Department of Biotechnology", programmeType: "RESEARCH_GRANT", supportType: ["research", "prototype"], fundingLabel: "Biotechnology innovation grant; current ceiling and call must be verified", fundingInstrument: "Grant", summary: "Early-stage support for ideas with substantive biotechnology or life-science innovation.", eligibilityRequirements: ["Substantive biotechnology or life-science innovation", "Application under a current BIG call"], hardRequirements: ["biotech_domain"], preferredDomains: ["BIOTECH"], preferredStages: ["idea", "proof_of_concept", "prototype"], supportedApplicantTypes: ["individual", "student", "researcher", "dpiit_startup", "startup_without_dpiit"], whatItSupports: ["Biotechnology proof of concept", "Validation", "Technology de-risking"], applicationMethod: "Apply through BIRAC or a BIG partner under a current call.", applicationSteps: ["Verify biotechnology fit", "Review the active call", "Submit the technical proposal through the official process"], officialPortal: "https://birac.nic.in/", officialSources: [source("BIRAC", "https://birac.nic.in/")] }),
  scheme({ id: "birac-sparsh", name: "BIRAC SPARSH", agency: "BIRAC", ministry: "Department of Biotechnology", programmeType: "FELLOWSHIP", supportType: ["fellowship", "social_impact", "research"], fundingLabel: "Social innovation fellowship/support; verify current programme call and terms", fundingInstrument: "Fellowship and incubation support", summary: "Supports social innovators addressing public-health and societal challenges through biotechnology-led solutions.", eligibilityRequirements: ["Relevant social innovation and programme-theme fit"], hardRequirements: [], preferredDomains: ["BIOTECH", "HEALTHCARE", "SOCIAL_IMPACT"], preferredStages: ["idea", "proof_of_concept"], supportedApplicantTypes: ["individual", "student", "researcher"], whatItSupports: ["Fellowship", "Immersion", "Mentoring", "Proof of concept"], applicationMethod: "Apply under an official SPARSH call through a participating centre.", applicationSteps: ["Review the active theme", "Confirm applicant eligibility", "Apply through the listed centre"], officialPortal: "https://birac.nic.in/", officialSources: [source("BIRAC programmes", "https://birac.nic.in/")] }),
  scheme({ id: "cgtmse", name: "Credit Guarantee Fund Trust for Micro and Small Enterprises (CGTMSE)", aliases: ["CGTMSE"], agency: "CGTMSE", ministry: "Ministry of MSME and SIDBI", programmeType: "CREDIT_GUARANTEE", supportType: ["loan", "msme"], fundingLabel: "Credit guarantee to eligible lenders; not a direct grant or loan from CGTMSE", fundingInstrument: "Credit guarantee", summary: "Guarantee cover supports collateral-free credit extended by eligible lending institutions to qualifying micro and small enterprises.", eligibilityRequirements: ["Eligible micro or small enterprise", "Credit sanctioned by a member lending institution"], hardRequirements: [], preferredDomains: generalDomains, preferredStages: ["prototype", "pilot", "market_ready", "revenue"], supportedApplicantTypes: ["micro", "small_entity", "existing_company"], whatItSupports: ["Credit access through eligible lenders"], applicationMethod: "Approach a member lending institution; the lender applies for guarantee cover.", applicationSteps: ["Confirm MSE eligibility", "Approach an eligible lender", "Complete the lender's credit appraisal"], officialPortal: "https://www.cgtmse.in/", officialSources: [source("CGTMSE official portal", "https://www.cgtmse.in/")] }),
  scheme({ id: "aspire", name: "ASPIRE", agency: "Ministry of MSME", ministry: "Ministry of Micro, Small and Medium Enterprises", programmeType: "INCUBATION_SUPPORT", supportType: ["incubation", "msme", "prototype"], fundingLabel: "Incubation and entrepreneurship support through approved institutions; not a universal direct grant", fundingInstrument: "Incubation and institutional support", summary: "Promotes innovation, rural industry and entrepreneurship through incubation infrastructure.", eligibilityRequirements: ["Fit with an eligible incubation or livelihood business incubator programme"], hardRequirements: [], preferredDomains: ["AGRITECH", "FOOD_TECH", "MANUFACTURING", "SOCIAL_IMPACT", "GENERAL_INNOVATION"], preferredStages: ["idea", "proof_of_concept", "prototype"], supportedApplicantTypes: ["individual", "micro", "small_entity", "startup_without_dpiit"], whatItSupports: ["Incubation", "Entrepreneurship development", "Rural and agro-industry innovation"], applicationMethod: "Engage with an institution operating under the current ASPIRE framework.", applicationSteps: ["Review current ASPIRE guidance", "Locate an eligible institution", "Apply under its published intake"], officialPortal: "https://aspire.msme.gov.in/", officialSources: [source("ASPIRE portal", "https://aspire.msme.gov.in/")] }),
  scheme({ id: "sipp", name: "Startup Intellectual Property Protection (SIPP)", aliases: ["SIPP"], agency: "DPIIT / CGPDTM", ministry: "Ministry of Commerce and Industry", programmeType: "IP_SUPPORT", supportType: ["ip", "startup"], fundingLabel: "Facilitator support and eligible fee concessions; statutory fees and current rules must be verified", fundingInstrument: "IP facilitation and fee support", summary: "Facilitates patent, trademark and design filings for eligible recognised startups.", eligibilityRequirements: ["DPIIT-recognised startup for startup-specific benefits"], hardRequirements: ["dpiit_yes"], preferredDomains: generalDomains, preferredStages: ["idea", "proof_of_concept", "prototype", "pilot", "market_ready"], supportedApplicantTypes: ["dpiit_startup"], whatItSupports: ["IP facilitator assistance", "Patent prosecution support", "Eligible fee concessions and expedited processes"], applicationMethod: "Use listed facilitators and verify current CGPDTM/Startup India rules.", applicationSteps: ["Verify DPIIT recognition", "Review the current SIPP rules", "Select an empanelled facilitator"], officialPortal: "https://www.startupindia.gov.in/content/sih/en/startup-scheme.html", officialSources: [source("Startup India scheme benefits", "https://www.startupindia.gov.in/content/sih/en/startup-scheme.html"), source("IP India", "https://ipindia.gov.in/")] }),
  scheme({ id: "patent-fee", name: "Patent fee concessions and expedited examination", agency: "CGPDTM", ministry: "Ministry of Commerce and Industry", programmeType: "IP_SUPPORT", supportType: ["ip"], fundingLabel: "Reduced statutory fees or expedited examination may apply to eligible categories; verify current Patent Rules", fundingInstrument: "Fee concession and procedural support", summary: "Certain applicant categories may access reduced patent fees and expedited examination under current rules.", eligibilityRequirements: ["Applicant must meet the applicable category definition"], hardRequirements: [], preferredDomains: generalDomains, preferredStages: ["idea", "proof_of_concept", "prototype", "pilot", "market_ready"], supportedApplicantTypes: ["individual", "dpiit_startup", "small_entity"], whatItSupports: ["Patent filing fee reduction", "Potential expedited examination"], applicationMethod: "File through IP India's official system using the correct applicant category.", applicationSteps: ["Verify applicant category", "Review current fee schedule", "Use the official e-filing portal or a qualified professional"], officialPortal: "https://ipindia.gov.in/", officialSources: [source("IP India", "https://ipindia.gov.in/")] }),
  scheme({ id: "meity-tide", name: "MeitY TIDE 2.0 and digital innovation programmes", aliases: ["TIDE 2.0"], agency: "MeitY Startup Hub", ministry: "Ministry of Electronics and Information Technology", programmeType: "INCUBATION_SUPPORT", supportType: ["prototype", "incubation", "startup"], fundingLabel: "Incubation and programme-specific financial support; verify current call and instrument", fundingInstrument: "Incubation, grant or challenge support depending on programme", summary: "Supports technology entrepreneurship in electronics and information technology through participating incubators and current calls.", eligibilityRequirements: ["Technology and current programme-call fit"], hardRequirements: [], preferredDomains: ["ELECTRONICS", "IOT", "SOFTWARE", "AI", "CYBERSECURITY", "HARDWARE"], preferredStages: ["idea", "proof_of_concept", "prototype", "pilot"], supportedApplicantTypes: startupApplicants, whatItSupports: ["Proof of concept", "Product development", "Incubation", "Market access"], applicationMethod: "Apply through the MeitY Startup Hub or participating centre under a current call.", applicationSteps: ["Review current programmes", "Confirm technology and stage fit", "Apply through the official programme channel"], officialPortal: "https://msh.meity.gov.in/", officialSources: [source("MeitY Startup Hub", "https://msh.meity.gov.in/")] }),
];

export function isDirectGrant(type: ProgrammeType) { return type === "DIRECT_GRANT" || type === "RESEARCH_GRANT"; }
