import type { TrademarkAnalysisProvider } from "./provider";
import { trademarkAIAnalysisSchema, type TrademarkAIAnalysis, type TrademarkProviderInput } from "./types";

const words = new Set(["water", "aqua", "pure", "smart", "best", "quality", "medical", "health", "digital", "eco"]);
function coined(root: string, suffix: string) { const value = `${root}${suffix}`.replace(/[^a-z0-9]/gi, "").slice(0, 80); return value[0]?.toUpperCase() + value.slice(1); }
export function unavailableTrademarkAIAnalysis(input: TrademarkProviderInput): TrademarkAIAnalysis { return trademarkAIAnalysisSchema.parse({ interpretation: `Conceptual AI analysis for ${input.brandName} is temporarily unavailable. Deterministic visual and phonetic screening is shown and can be retried.`, conceptualCandidates: [], distinctivenessAssessment: { classification: "UNCERTAIN", explanation: "Distinctiveness requires review because conceptual analysis was unavailable.", professionalReviewNeeded: true }, possibleIndustryReferences: [], relatedClassSuggestions: [], alternativeNames: [], assumptions: ["Only deterministic similarity checks completed."], verificationWarnings: ["Conceptual analysis could not be completed. Retry when the configured provider is available."], disclaimer: "This automated report analyses name similarity and available evidence. It does not confirm trademark availability, registrability, ownership or freedom to use the name." }); }
export class MockTrademarkAnalysisProvider implements TrademarkAnalysisProvider {
  readonly name = "mock"; readonly version = "1.0.0";
  async analyseTrademark(input: TrademarkProviderInput): Promise<TrademarkAIAnalysis> {
    const lower = input.normalizedName; const aqua = /aqua|water|hydro|jal|pani/.test(`${lower} ${input.languageMeaning} ${input.goodsServicesDescription}`);
    const conceptual = aqua ? [
      { name: "WaterSense", meaning: "Water-related sensing", language: "English", similarityExplanation: "Uses an English equivalent of the water concept with the same Sense element.", source: "AI_GENERATED" as const, verifiedConflict: false as const },
      { name: "HydroSense", meaning: "Water sensing", language: "Greek-derived English", similarityExplanation: "Replaces Aqua with the conceptually related Hydro element.", source: "AI_GENERATED" as const, verifiedConflict: false as const },
      { name: "JalSense", meaning: "Water sensing", language: "Hindi", similarityExplanation: "Uses Jal as a supplied-context translation concept while retaining Sense.", source: "AI_GENERATED" as const, verifiedConflict: false as const },
    ] : [{ name: `${input.brandName} Concept`, meaning: "Conceptually related naming direction", language: null, similarityExplanation: "Retains the proposed name while signalling a conceptual variation.", source: "AI_GENERATED" as const, verifiedConflict: false as const }];
    const descriptive = input.tokens.some((token) => words.has(token)) || input.tokens.some((token) => input.goodsServicesDescription.toLowerCase().includes(token));
    const alternatives = ["Nexora", "Veylix", "Orivanta", "Cyntra"].map((name) => ({ name: coined(input.tokens[0] ?? "invent", name), rationale: "Creates a more coined naming direction for preliminary screening.", productConnection: input.invention ? `Intended as a naming direction for ${input.invention.title}.` : "Maintains a product-brand naming structure.", distinctivenessEstimate: "FANCIFUL_OR_COINED" as const, similarityWarning: "Unverified — run a new trademark search.", domainStatus: "NOT_CHECKED" as const, socialStatus: "NOT_CHECKED" as const, verificationRequired: true as const })).slice(0, 4);
    const distinctivenessExplanation = descriptive
      ? aqua && /sense/.test(lower)
        ? "‘Aqua’ and ‘Sense’ may describe water-related sensing, so the name could have limited inherent distinctiveness for water-monitoring products. This is not a legal registrability conclusion."
        : "The name contains wording that may describe a characteristic or subject of the supplied goods or services. Review distinctiveness against the exact filing wording."
      : "The available context is insufficient for a reliable distinctiveness classification.";
    return trademarkAIAnalysisSchema.parse({ interpretation: `The proposed name is screened for class ${input.niceClass} using the supplied goods or services context.`, conceptualCandidates: conceptual.slice(0, 15), distinctivenessAssessment: { classification: descriptive ? "DESCRIPTIVE" : "UNCERTAIN", explanation: distinctivenessExplanation, professionalReviewNeeded: true }, possibleIndustryReferences: input.tokens.filter((token) => words.has(token)), relatedClassSuggestions: input.invention && /pill|medicine|medical/i.test(`${input.invention.title} ${input.invention.proposedSolution}`) ? [{ niceClass: 10, reason: "Medical apparatus may fall within Class 10." }, { niceClass: 9, reason: "Relevant electronic control or downloadable software goods may require Class 9 review." }, { niceClass: 42, reason: "Class 42 is relevant only for separately provided software or technology services." }] : [], alternativeNames: alternatives, assumptions: ["No registry ownership or registration status is inferred."], verificationWarnings: ["Generated candidates are not verified registry conflicts."], disclaimer: "This automated report analyses name similarity and available evidence. It does not confirm trademark availability, registrability, ownership or freedom to use the name." });
  }
}
